#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "running cowtest")
def test_cowtest():
    r.run_qemu(shell_script([
        'cowtest'
    ]))

@test(15, "simple", parent=test_cowtest)
def test_simple():
    matches = re.findall("^simple: ok$", r.qemu.output, re.M)
    assert_equal(len(matches), 2, "Number of appearances of 'simple: ok'")

@test(15, "three", parent=test_cowtest)
def test_three():
    matches = re.findall("^three: ok$", r.qemu.output, re.M)
    assert_equal(len(matches), 3, "Number of appearances of 'three: ok'")

@test(10, "file", parent=test_cowtest)
def test_file():
    r.match('^file: ok$')

@test(0, "running threadtest")
def test_threadtest():
    r.run_qemu(shell_script([
        'threadtest'
    ]))

@test(20, "threadtest: testthreadrun", parent=test_threadtest)
def test_threadtest_testthreadrun():
    r.match('^testthreadrun passed$')

@test(20, "threadtest: testthreadmore", parent=test_threadtest)
def test_threadtest_testthreadmore():
    r.match('^\\.?testthreadmore passed$')

@test(15, "threadtest: testthreadsbrk", parent=test_threadtest)
def test_threadtest_testthreadsbrk():
    r.match('^\\.?testthreadsbrk passed$')

run_tests()
