#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(35, "running bigfile")
def test_bigfile():
    r.run_qemu(shell_script([
        'bigfile'
    ]), timeout=3600)
    r.match('^wrote 65803 blocks$')
    r.match('^bigfile done; ok$')

@test(0, "running symlinktest")
def test_symlinktest():
    r.run_qemu(shell_script([
        'symlinktest'
    ]), timeout=20)

@test(15, "symlinktest: symlinks", parent=test_symlinktest)
def test_symlinktest_symlinks():
    r.match("^test symlinks: ok$")

@test(15, "symlinktest: concurrent symlinks", parent=test_symlinktest)
def test_symlinktest_symlinks():
    r.match("^test concurrent symlinks: ok$")

@test(0, "running aiotest")
def test_aiotest():
    r.run_qemu(shell_script([
        'aiotest'
    ]), timeout=600)

@test(15, "aiotest: 20 read / write", parent=test_symlinktest)
def test_aiotest_test20():
    r.match("^test20: ok$")

@test(20, "symlinktest: concurrent symlinks", parent=test_symlinktest)
def test_aiotest_test100():
    r.match("^test1000: ok$")

run_tests()
